languageCode = "en"
languageName = "English"
weight = 1
title = "nveshaan"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "nveshaan's portfolio"
secondaryLogo = "second_logo.png"

[author]
name = "Eshaan"
headline = "20yo // tinkerer, researcher, and engineer // deep learning in medicine"
image = "profile.jpeg"
links = [ { envelope = "mailto:nveshaan23@iisertvm.ac.in" }, { github = "https://github.com/nveshaan" }, { x-twitter = "https://x.com/nveshaan" }, { linkedin = "https://www.linkedin.com/in/nveshaan"}, { codeforces = "https://codeforces.com/profile/nveshaan" } ]
bio = "Undergrad at IISER Thiruvananthapuram"
