# -- Markup --
# These settings are required for the theme to function.

[goldmark]
  [goldmark.renderer]
    unsafe = true

[highlight]
  noClasses = true       # Tells Hugo to use its own built-in theme colors
  style = "monokai"      # Options: monokai, github-dark, solarized-dark, pygments, etc.
  codeFences = true
  guessSyntax = true

[tableOfContents]
  startLevel = 2
  endLevel = 4
